# This is a generated file. Not intended for manual editing.
services:
  auth:
    build:
      context: "/home/shmi/RiderProjects/WeatherApp"
      dockerfile: "AuthService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AuthService.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "authservice:dev"
    ports: []
    volumes:
    - "/home/shmi/RiderProjects/WeatherApp/AuthService:/app:rw"
    - "/home/shmi/RiderProjects/WeatherApp:/src:rw"
    - "/home/shmi/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
